--
-- PostgreSQL database dump
--

-- Dumped from database version 12.8
-- Dumped by pg_dump version 13.1

-- Started on 2022-03-04 08:22:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 49186)
-- Name: country_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country_product (
    id bigint NOT NULL,
    country character varying(150)
);


ALTER TABLE public.country_product OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 49178)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    color character varying(255),
    country character varying(255),
    img character varying(255),
    name character varying(255),
    price integer,
    strong double precision,
    sugar_content character varying(255),
    country_id bigint
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 49176)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2825 (class 0 OID 49186)
-- Dependencies: 204
-- Data for Name: country_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.country_product (id, country) VALUES (1, 'Россия');
INSERT INTO public.country_product (id, country) VALUES (2, 'Франция');
INSERT INTO public.country_product (id, country) VALUES (3, 'Италия');
INSERT INTO public.country_product (id, country) VALUES (4, 'Аргентина');
INSERT INTO public.country_product (id, country) VALUES (5, 'Грузия');


--
-- TOC entry 2824 (class 0 OID 49178)
-- Dependencies: 203
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product (id, color, country, img, name, price, strong, sugar_content, country_id) VALUES (1, 'Красное', 'Аргентина', '0_0.jpg', 'Cabernet Sauvignon
Finca La Linda', 987, 13.4, 'сухое', NULL);
INSERT INTO public.product (id, color, country, img, name, price, strong, sugar_content, country_id) VALUES (2, 'Красное', 'Франция', '0_1.jpg', 'Mouton Cadet,
Bordeaux AOC Rouge', 1028, 13.5, 'сухое', 2);
INSERT INTO public.product (id, color, country, img, name, price, strong, sugar_content, country_id) VALUES (3, 'Белое', 'Италия', '0_2.jpg', 'Feudi del Pisciotto,
Baglio del Sole', 768, 12.5, 'сухое', NULL);
INSERT INTO public.product (id, color, country, img, name, price, strong, sugar_content, country_id) VALUES (4, 'Игристое белое', 'Россия', '0_3.jpg', 'Abrau-Durso, Brut', 383, 12.5, 'сухое', NULL);


--
-- TOC entry 2831 (class 0 OID 0)
-- Dependencies: 202
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 5, true);


--
-- TOC entry 2695 (class 2606 OID 49190)
-- Name: country_product country_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country_product
    ADD CONSTRAINT country_product_pkey PRIMARY KEY (id);


--
-- TOC entry 2693 (class 2606 OID 49185)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- TOC entry 2696 (class 2606 OID 49191)
-- Name: product foregKeyIdcoun; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "foregKeyIdcoun" FOREIGN KEY (country_id) REFERENCES public.country_product(id) NOT VALID;


-- Completed on 2022-03-04 08:22:34

--
-- PostgreSQL database dump complete
--

